### ISSUE TITLE
Question: Just use one stage?

### ISSUE THREAD

**Issue by tobilg** [jacob-meacham/serverless-plugin-bind-deployment-id#16]
Thanks for your work on this plugin! I have a question, is it possible to just use one stage? I see that if I stick to the example, a stage named `__unused_stage__` is created additionally to my already existing stage `dev`. 

I'd really prefer if it'd be possible to just have one, and to be honest I didn't really get the explanation under https://www.npmjs.com/package/serverless-plugin-bind-deployment-id#known-issues Could you eventually clarify this a bit? Thanks a lot in advance!

**Comment by tobilg** [comment]
As a follow up, I just tried doing this:

```yaml
Resources:
  ApiGatewayAccessLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: ${self:custom.apiGateway.accessLogGroupName}
        RetentionInDays: ${self:custom.apiGateway.accessLogRetentionInDays}
  __deployment__:
    Properties:
      Description: The API Gateway deployment
      StageName: ${self:provider.stage}
  ApiGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId:
        Ref: __deployment__
      RestApiId:
        Ref: ApiGatewayRestApi
      StageName: ${self:provider.stage}
      TracingEnabled: false
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          LoggingLevel: INFO
          MetricsEnabled: true
          DataTraceEnabled: false
      AccessLogSetting:
        Format: '{"apiId":"$context.apiId","stage":"$context.stage","resourcePath":"$context.resourcePath","requestId":"$context.requestId","awsEndpointRequestId":"$context.awsEndpointRequestId","xrayTraceId":"$context.xrayTraceId","requestTime":"$context.requestTime","requestTimeEpoch":$context.requestTimeEpoch,"httpMethod":"$context.httpMethod","status":"$context.status","path":"$context.path"}'
        DestinationArn: '#{ApiGatewayAccessLogGroup.Arn}'
```

and this seems to work so that only one stage is created. Is this fine from your perspective?
