### ISSUE TITLE
Issue with reference to deployment

### ISSUE THREAD

**Issue by AbdullahAli** [jacob-meacham/serverless-plugin-bind-deployment-id#37]
I hope you are well,

I am following the example in the plugin page as follows:

```
resources:
  Resources:
    __deployment__:
      Properties:
        Description: This is my deployment

    ApiGatewayStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        StageName: ${self:provider.stage}
        DeploymentId:
          Ref: __deployment__
        ApiId:
          Ref: ApiGatewayRestApi
        AutoDeploy: true
```

However, it keeps giving me an error as follows:
```
  An error occurred: ApiGatewayStage - Invalid API identifier specified xxxxxxxxxx:XXXXXXXX (Service: AmazonApiGatewayV2; Status Code: 404; Error Code: NotFoundException; Request ID: e7ff26bd-99a8-4b1c-a9a0-d494c796aaf2; Proxy: null).
```

I was wondering if you are able to help please?
