### ISSUE TITLE
Every Resources object must contain a Type member

### ISSUE THREAD

**Issue by FritzSG** [jacob-meacham/serverless-plugin-bind-deployment-id#4]
When I attempt to implement your solution I get the following error:

  Serverless Error ---------------------------------------
 
     Template format error: [/Resources/__deployment__] Every
     Resources object must contain a Type member.

my serverless.yml Sanitized
``` yaml
provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  timeout: 15
  versionFunctions: false
  role: arn:aws:iam::sanitized
  vpc:
    securityGroupIds:
      - sg-sanitized
    subnetIds:
      - subnet-sanitized
      - subnet-sanitized
  region: us-west-2
  apiKeys:
    - workaroundkey
package:
  exclude:
    - node_modules/**
functions:
  auth:
    handler: sanitized
    name: sanitized-${opt:stage}
    description: Pre-Authentication Lambda
    events:
      - http: POST auth
  oauth:
    handler: sanitized.sanitized
    name: sanitized-${opt:stage}
    description: App oauth Lambda
    events:
      - http: GET oauth        
      - http: POST oauth
resources:
  Resources:
    pathmapping:
      DependsOn: ApiGatewayApiKey1
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: ${opt:stage}
        DomainName: sanitized
        RestApiId: __deployment__
        Stage: ${opt:stage}
    __deployment__:
      Properties:
        DataTraceEnabled: true
        MetricsEnabled: true
plugins:
  - serverless-plugin-bind-deployment-id
```

**Comment by jacob-meacham** [comment]
Hi @FritzSG - sorry for the trouble you've had! I'll be sure to take a look at this tonight and let you know what's going on. Thanks!

**Comment by jacob-meacham** [comment]
What version of serverless are you running?

**Comment by jacob-meacham** [comment]
As I just discussed in the README, right now you have to, unfortunately, make a different stage with a stable id. These stages are pretty simple to ignore, since they never show up anywhere - we're currently deploying ~20 microservices across staging and prod right now, and haven't had a problem with them. The way I'd structure your resources from above:

```yaml
resources:
  Resources:
    pathmapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: ${opt:stage}
        DomainName: sanitized
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${opt:stage}
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId:
          Ref: __deployment__
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName : ${opt:stage}
        MethodSettings:
          - DataTraceEnabled: true
            MetricsEnabled: true
```

Notice that you shouldn't have to use an API key workaround anymore either.
